// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xyvnqtjxnlongywzhhnd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh5dm5xdGp4bmxvbmd5d3poaG5kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0Mzc0ODcsImV4cCI6MjA3MzAxMzQ4N30.hVEutxPFwQpTeqOiE1zlXcGH5WEdG-28w-ctjZLny5w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// For Clerk integration, use the useSupabaseClient hook instead
// import { useSupabaseClient } from "@/hooks/useSupabaseClient";